name: CI/CD for Angular Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js environment
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    # Step 3: Install dependencies
    - name: Install Dependencies
      run: npm install

    # Step 4: Build the Angular application
    - name: Build Application
      run: npm run build --prod

    # Step 5: Build Docker image
    - name: Build Docker Image
      run: |
        docker build -t angular-app:latest .

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up SSH for server deployment
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # Step 3: Copy Docker image to the server
    - name: Copy Docker Image
      run: |
        scp docker-compose.yml ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home/${{ secrets.SERVER_USER }}/

    # Step 4: Run Docker container on server
    - name: Run Docker Container
      run: |
        ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
        docker stop angular-app || true
        docker rm angular-app || true
        docker run -d --name angular-app -p 8100:80 angular-app:latest
        EOF
