name: Automatic Version Tagging

on:
  push:
    branches:
      - master  # Set the branch where versioning should occur

jobs:
  tag-version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js (optional, if you need node/npm)
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Get the latest tag or create an initial tag
      run: |
        TAGS=$(git tag -l)
        if [ -z "$TAGS" ]; then
          NEW_TAG="v0.0.1"
        else
          # Sort tags numerically to get the latest tag
          LATEST_TAG=$(echo "$TAGS" | sort -V | tail -n 1)
          # Increment the PATCH version
          VERSION_ARRAY=(${LATEST_TAG//./ })
          PATCH=${VERSION_ARRAY[2]}
          NEW_PATCH=$((PATCH + 1))
          NEW_TAG="${VERSION_ARRAY[0]}.${VERSION_ARRAY[1]}.$NEW_PATCH"
        fi
        echo "New version is: $NEW_TAG"
        echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

    - name: Create new version tag
      run: |
        git tag $NEW_TAG
        git push origin $NEW_TAG
