name: CI/CD Pipeline for Docker Deployment

on:
  push:
    tags:  # Trigger the workflow on new tags
      - "v*"

env:
  IMAGE_NAME: sanjayraj/cocaptan  # Replace with your Docker Hub repository

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Extract Version from Git Tag
      - name: Get Git Tag
        id: git_tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:$TAG .

      # Step 5: Push Docker Image to Docker Hub
      - name: Push Docker Image to Docker Hub
        run: |
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$TAG

      # Step 6: Set up SSH to Deploy to Remote Server
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $HOST >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.HOST }}

      # Step 7: Deploy to Remote Server
      - name: Deploy Application to Droplet
        run: |
          ssh root@$HOST "
            docker pull $IMAGE_NAME:$TAG &&
            docker stop cocaptan || true &&
            docker rm cocaptan || true &&
            docker run -d --name cocaptan -p 4200:4200 $IMAGE_NAME:$TAG --host 0.0.0.0
          "
        env:
          HOST: ${{ secrets.HOST }}
