name: SSH Connection Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Debug secrets and validate environment variables
      - name: Debug Environment Variables
        run: |
          echo "HOST environment variable: '$HOST'"
          echo "SSH_PRIVATE_KEY length: ${#SSH_PRIVATE_KEY}"
          if [ -z "$HOST" ]; then
            echo "ERROR: HOST variable is not set or empty!"
            exit 1
          fi
        env:
          HOST: ${{ secrets.HOST }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      # Set up SSH key and known_hosts
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "Setting up known_hosts for host: $HOST"
          ssh-keyscan -H "$HOST" >> ~/.ssh/known_hosts
        env:
          HOST: ${{ secrets.HOST }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      # Test SSH Connection
      - name: Test SSH Connection
        run: |
          ssh -o StrictHostKeyChecking=no root@$HOST 'echo "SSH connection successful"'
        env:
          HOST: ${{ secrets.HOST }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
