name: Automatic Version Tagging

on:
  push:
    branches:
      - master  # Set the branch where versioning should occur

jobs:
  tag-version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js (optional, if you need node/npm)
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Get the latest tag or create an initial tag
      run: |
        TAG=$(git describe --tags --abbrev=0 || echo "v0.0.0")
        echo "Latest tag is: $TAG"
        echo "TAG=$TAG" >> $GITHUB_ENV

    - name: Increment version number
      run: |
        VERSION=$(echo $TAG | sed 's/\([0-9]*\)\.\([0-9]*\)\.\([0-9]*\)/\1.\2.\3/')
        VERSION_ARRAY=(${VERSION//./ })
        PATCH=${VERSION_ARRAY[2]}
        NEW_PATCH=$((PATCH + 1))
        NEW_VERSION="${VERSION_ARRAY[0]}.${VERSION_ARRAY[1]}.$NEW_PATCH"
        echo "New version is: $NEW_VERSION"
        echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

    - name: Create new version tag
      run: |
        git tag $NEW_VERSION
        git push origin $NEW_VERSION
