name: CI/CD Pipeline for Docker Deployment

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: sanjayraj/cocaptan  # Replace with your Docker Hub repository

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Determine Next Version Tag
      - name: Determine Next Version Tag
        id: version
        run: |
          latest_tag=$(git tag --sort=-v:refname | head -n 1)
          if [[ "$latest_tag" =~ ^v([0-9]+)$ ]]; then
            version_number=${BASH_REMATCH[1]}
            next_version=$((version_number + 1))
          else
            next_version=1
          fi
          new_tag="v$next_version"
          echo "TAG_NAME=$new_tag" >> $GITHUB_ENV
        shell: bash

      # Step 4: Build Docker Image
      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME:$TAG_NAME .

      # Step 5: Push Docker Image to Docker Hub
      - name: Push Docker Image to Docker Hub
        run: docker push $IMAGE_NAME:$TAG_NAME

      # Step 6: Push New Git Tag (only if it doesn't exist already)
      - name: Push New Git Tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git fetch --tags
          # Check if the tag exists
          if git rev-parse $TAG_NAME >/dev/null 2>&1; then
            echo "Tag $TAG_NAME already exists, skipping push."
          else
            git tag $TAG_NAME
            git push origin $TAG_NAME
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
