name: CI/CD Pipeline for Docker Deployment

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: sanjayraj/cocaptan  # Replace with your Docker Hub repository

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
        - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build Docker Image with Dynamic Tag (based on commit SHA or GitHub Run)
      - name: Build Docker Image
        run: |
          IMAGE_TAG="v$(git rev-list --count HEAD)"
          # Ensure tag is valid for Docker (e.g., no starting digits)
          if [[ ! "$IMAGE_TAG" =~ ^[a-zA-Z] ]]; then
            IMAGE_TAG="v1"
          fi
          echo "Building image with tag: $IMAGE_TAG"
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
        env:
          IMAGE_NAME: ${{ secrets.IMAGE_NAME }}

      # Step 4: Push Docker Image to Docker Hub with Dynamic Tag
      - name: Push Docker Image to Docker Hub
        run: |
          IMAGE_TAG="v$(git rev-list --count HEAD)"
          # Ensure tag is valid for Docker (e.g., no starting digits)
          if [[ ! "$IMAGE_TAG" =~ ^[a-zA-Z] ]]; then
            IMAGE_TAG="v1"
          fi
          docker push $IMAGE_NAME:$IMAGE_TAG
        env:
          IMAGE_NAME: ${{ secrets.IMAGE_NAME }}

      # Step 5: Set up SSH to Deploy to Remote Server
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $HOST >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.HOST }}

      # Step 6: Deploy to Remote Server
      - name: Deploy Application to Droplet
        run: |
          IMAGE_TAG="v$(git rev-list --count HEAD)"
          # Ensure tag is valid for Docker (e.g., no starting digits)
          if [[ ! "$IMAGE_TAG" =~ ^[a-zA-Z] ]]; then
            IMAGE_TAG="v1"
          fi
          ssh root@$HOST "
            docker pull $IMAGE_NAME:$IMAGE_TAG &&
            docker stop cocaptan || true &&
            docker rm cocaptan || true &&
            docker run -d --name cocaptan -p 4200:4200 $IMAGE_NAME:$IMAGE_TAG --host 0.0.0.0
          "
        env:
          HOST: ${{ secrets.HOST }}
