name: SSH Connection Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Check out the code from GitHub
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up SSH key
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $HOST >> ~/.ssh/known_hosts

      # SSH into remote server
      - name: SSH to Remote Server
        run: |
          ssh -o StrictHostKeyChecking=no root@$HOST 'echo "SSH connection successful"'
        env:
          HOST: ${{ secrets.HOST }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
